
public class EvenFibonacci {

	public static void main(String[] args) {
		/*Each new term in the Fibonacci sequence is generated by adding the previous two terms. 
		 * By starting with 1 and 2, the first 10 terms will be: 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
		 * By considering the terms in the Fibonacci sequence whose values do not exceed four million,
		 * find the sum of the even-valued terms.
		 */

		long termOne = 0;
		long termTwo = 1;
		long sum;
		long evenSum = 0;
		
		for (int i=0; i<35; i++) {
			sum = termOne+termTwo;
			
			if (sum % 2 == 0 && sum <= 4000000) {
				evenSum = evenSum + sum;
			}
			
			
			termOne = termTwo;
			termTwo = sum;
			
		}
		
		System.out.print("The sum of even fibonacci numbers which do not exceed 4 million is " + evenSum);

	}

}
